name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: chipmunk25/clinton-store
  CONTAINER_NAME: clinton-store
  HOST_PORT: 3015
  CONTAINER_PORT: 3000
  NEXT_PUBLIC_APP_URL: https://clintonstore@gigiandsiri.com
  DATABASE_URL: postgresql://user:password@dbhost:5432/clinton_store_db
  AUTH_SECRET: Q9vM3kA7xR5JZp2FhC8NwE6SByD4LqT0Uo1eIYHgsrKmZcWVaP

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest
          no-cache: true
          build-args: |
            NEXT_PUBLIC_APP_URL=${{ env.NEXT_PUBLIC_APP_URL }}
            AUTH_SECRET=${{ env.AUTH_SECRET }}
            DATABASE_URL=${{ env.DATABASE_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOCKER_IMAGE_NAME: ${{ env.DOCKER_IMAGE_NAME }}
          CONTAINER_NAME: ${{ env.CONTAINER_NAME }}
          HOST_PORT: ${{ env.HOST_PORT }}
          CONTAINER_PORT: ${{ env.CONTAINER_PORT }}
          NEXT_PUBLIC_BASE_URL: ${{ env.NEXT_PUBLIC_BASE_URL }}

        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_USERNAME }}"@"${{ secrets.SSH_HOST }}" -p "${{ secrets.SSH_PORT }}" << EOF
            echo "Logging in to Docker Hub"
            docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'

            echo "Pulling the latest Docker image: ${DOCKER_IMAGE_NAME}:latest"
            docker pull "${DOCKER_IMAGE_NAME}:latest"

            echo "Stopping and removing the existing container if it exists"
            if [ \$(docker ps -a | grep "${CONTAINER_NAME}" | wc -l) -gt 0 ]; then
              docker stop "${CONTAINER_NAME}"
              docker rm "${CONTAINER_NAME}"
            fi

            echo "Ensuring 'sail' network exists"
            docker network inspect sail >/dev/null 2>&1 || docker network create sail

            echo "Pruning unused Docker images"
            docker image prune -a -f

            echo "Running the new Docker container with env vars"
            docker run -d --restart always --net sail -p "${HOST_PORT}:${CONTAINER_PORT}" --name "${CONTAINER_NAME}" \
              --env NEXT_PUBLIC_APP_URL="${NEXT_PUBLIC_APP_URL}" \
              --env DATABASE_URL="${DATABASE_URL}" \
              --env AUTH_SECRET="${AUTH_SECRET}" \
              "${DOCKER_IMAGE_NAME}:latest"
          EOF
